# Generated by Django 4.2.3 on 2023-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_bookstoremodel_last_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='about',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
